GPPPARAMS = -m32 
GPPPARAMS = --32
LDPARAMS = -melf_i386

object = loader.o kernel.o 

%.o: %.cpp
	g++ ${GPPPARAMS} -o $@ -c $<

%.o: %.s
	as ${GPPPARAMS} -o $@ -c $<

mykernel.bin: linker.ld ${objects}
	ld ${LDPARAMS} -T $< -o $@ ${objects}

install: mykernel.bin
	sudo cp $<  /boot/mykernel.bin	